# Configuración de archivos para releases de odoodevs
# Autor: Mauro Rosero Pérez

# Archivos principales que se incluyen en todos los releases
main_files:
  - bin/odoo-create.sh
  - bin/odoo-image.sh
  - bin/odoodevs-path.sh
  - bin/odevs-manager.sh
  - bin/odevs-fixperms.sh
  - bin/.odoodevs
  - bin/.created
  - bin/.updated

# Directorios que se incluyen completos
directories:
  - scaffolding
  - docs

# Archivos de configuración del proyecto
config_files:
  - VERSION
  - RELEASE_INFO

# Archivos opcionales que se pueden incluir según el tipo de release
optional_files:
  # Archivos de documentación
  documentation:
    - README.md
    - LICENSE
    - CHANGELOG.md
  
  # Archivos de desarrollo
  development:
    - .gitignore
    - docs/RELEASE.md
    - odevs-buildrel.sh
    - odevs-delrel.sh
    - odevs-newrel.sh
  
  # Archivos de configuración del proyecto
  project_config:
    - configs/release-config.yml

# Configuración por tipo de release
release_types:
  # Release completo (incluye todo)
  full:
    include_main: true
    include_directories: true
    include_config: true
    include_optional:
      - documentation
      - development
      - project_config
  
  # Release de usuario (solo lo necesario para usar)
  user:
    include_main: true
    include_directories: true
    include_config: true
    include_optional:
      - documentation
  
  # Release mínimo (solo archivos principales)
  minimal:
    include_main: true
    include_directories: true
    include_config: true
    include_optional: []

# Configuración por defecto
default_release_type: "user"

# Patrones de exclusión (archivos que nunca se incluyen)
exclude_patterns:
  # Archivos temporales y logs
  - "*.tmp"
  - "*.log"
  - ".DS_Store"
  - "Thumbs.db"
  - "*.swp"
  - "*.swo"
  - "*~"
  
  # Archivos de configuración sensible
  - ".env"
  - "*.key"
  - "*.pem"
  - "*.p12"
  
  # Directorios de proyectos (no incluidos en release)
  - "clientes/*"
  - "verticales/*"
  - "modulos/*"
  - "sops/*"
  
  # Plantillas Jinja2 (no incluidas en release)
  - "*.j2"
  
  # Archivos específicos de Python
  - "__pycache__/"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - ".Python"
  - "build/"
  - "develop-eggs/"
  - "dist/"
  - "downloads/"
  - "eggs/"
  - ".eggs/"
  - "lib/"
  - "lib64/"
  - "parts/"
  - "sdist/"
  - "var/"
  - "wheels/"
  - "*.egg-info/"
  - ".installed.cfg"
  - "*.egg"
  
  # Entornos virtuales de Python
  - "venv/"
  - "env/"
  - ".venv/"
  - ".env/"
  - "ENV/"
  - "env.bak/"
  - "venv.bak/"
  
  # Herramientas de desarrollo Python
  - ".pytest_cache/"
  - ".coverage"
  - "htmlcov/"
  - ".tox/"
  - ".nox/"
  - "coverage.xml"
  - "*.cover"
  - ".hypothesis/"
  
  # IDEs y editores
  - ".vscode/"
  - ".idea/"
  - "*.sublime-*"
  - ".spyderproject"
  - ".spyproject"
